// henrique agostinetto piva
using AcademiaDoZe.Application.DTOs;
using AcademiaDoZe.Application.Enums;

namespace AcademiaDoZe.Application.Interfaces;

public interface ILogradouroService { Task<LogradouroDto?> ObterPorIdAsync(int id, CancellationToken cancellationToken = default); Task<IEnumerable<LogradouroDto>> ObterTodosAsync(CancellationToken cancellationToken = default); Task<LogradouroDto> AdicionarAsync(LogradouroDto dto, CancellationToken cancellationToken = default); Task<LogradouroDto> AtualizarAsync(LogradouroDto dto, CancellationToken cancellationToken = default); Task<bool> RemoverAsync(int id, CancellationToken cancellationToken = default); Task<LogradouroDto?> ObterPorCepAsync(string cep, CancellationToken cancellationToken = default); Task<bool> CepJaExisteAsync(string cep, int? id = null, CancellationToken cancellationToken = default); Task<IEnumerable<LogradouroDto>> ObterPorCidadeAsync(string cidade, CancellationToken cancellationToken = default); Task<IEnumerable<LogradouroDto>> ObterPorBairroAsync(string cidade, string bairro, CancellationToken cancellationToken = default); }
public interface IAlunoService { Task<AlunoDto?> ObterPorIdAsync(int id, CancellationToken cancellationToken = default); Task<IEnumerable<AlunoDto>> ObterTodosAsync(CancellationToken cancellationToken = default); Task<AlunoDto> AdicionarAsync(AlunoDto dto, CancellationToken cancellationToken = default); Task<AlunoDto> AtualizarAsync(AlunoDto dto, CancellationToken cancellationToken = default); Task<bool> RemoverAsync(int id, CancellationToken cancellationToken = default); Task<AlunoDto?> ObterPorCpfAsync(string cpf, CancellationToken cancellationToken = default); Task<AlunoDto?> ObterPorEmailAsync(string email, CancellationToken cancellationToken = default); Task<IEnumerable<AlunoDto>> ObterPorNomeAsync(string nome, CancellationToken cancellationToken = default); Task<bool> CpfJaExisteAsync(string cpf, int? id = null, CancellationToken cancellationToken = default); Task<bool> EmailJaExisteAsync(string email, int? id = null, CancellationToken cancellationToken = default); Task<bool> TrocarSenhaAsync(int id, string senha, CancellationToken cancellationToken = default); }
public interface IColaboradorService { Task<ColaboradorDto?> ObterPorIdAsync(int id, CancellationToken cancellationToken = default); Task<IEnumerable<ColaboradorDto>> ObterTodosAsync(CancellationToken cancellationToken = default); Task<ColaboradorDto> AdicionarAsync(ColaboradorDto dto, CancellationToken cancellationToken = default); Task<ColaboradorDto> AtualizarAsync(ColaboradorDto dto, CancellationToken cancellationToken = default); Task<bool> RemoverAsync(int id, CancellationToken cancellationToken = default); Task<ColaboradorDto?> ObterPorCpfAsync(string cpf, CancellationToken cancellationToken = default); Task<ColaboradorDto?> ObterPorEmailAsync(string email, CancellationToken cancellationToken = default); Task<IEnumerable<ColaboradorDto>> ObterPorTipoAsync(AppColaboradorTipo tipo, CancellationToken cancellationToken = default); Task<IEnumerable<ColaboradorDto>> ObterPorVinculoAsync(AppColaboradorVinculo vinculo, CancellationToken cancellationToken = default); Task<bool> CpfJaExisteAsync(string cpf, int? id = null, CancellationToken cancellationToken = default); Task<bool> EmailJaExisteAsync(string email, int? id = null, CancellationToken cancellationToken = default); Task<bool> TrocarSenhaAsync(int id, string senha, CancellationToken cancellationToken = default); }
public interface IMatriculaService { Task<MatriculaDto?> ObterPorIdAsync(int id, CancellationToken cancellationToken = default); Task<IEnumerable<MatriculaDto>> ObterTodasAsync(CancellationToken cancellationToken = default); Task<MatriculaDto> AdicionarAsync(MatriculaDto dto, CancellationToken cancellationToken = default); Task<MatriculaDto> AtualizarAsync(MatriculaDto dto, CancellationToken cancellationToken = default); Task<bool> RemoverAsync(int id, CancellationToken cancellationToken = default); Task<IEnumerable<MatriculaDto>> ObterPorAlunoIdAsync(int alunoId, CancellationToken cancellationToken = default); Task<MatriculaDto?> ObterMatriculaAtivaPorAlunoAsync(int alunoId, CancellationToken cancellationToken = default); Task<bool> PossuiMatriculaAtivaAsync(int alunoId, CancellationToken cancellationToken = default); Task<IEnumerable<MatriculaDto>> ObterAtivasAsync(int alunoId = 0, CancellationToken cancellationToken = default); Task<IEnumerable<MatriculaDto>> ObterVencendoEmDiasAsync(int dias, CancellationToken cancellationToken = default); Task<IEnumerable<MatriculaDto>> ObterPorPlanoAsync(AppMatriculaPlano plano, CancellationToken cancellationToken = default); }
